### PR TITLE
add new basic section and website optimization

### PR DESCRIPTION
**Pull request by MaikenGunnerod**

### CODE REVIEW

**Comment by MaikenGunnerod** [comment]
Added new "Extra content" section on videopage:
- h2 "Extra content"
- YouTube embed
- p element for buttons section
- Social buttons (twitch, 2x tiktok)

Added a meta description to the website

**Comment by MaikenGunnerod** [comment]
Made changes to content buttons:
- Changed colour to a red gradient

**Comment by MaikenGunnerod** [comment]
Added correct link to SAI twitch button:
- Now leads to "OMOweatherman" twitch

**Comment by MaikenGunnerod** [comment]
Added icons to extra content buttons:

- Added twitch and tiktok logos
- Removed width property  on buttons and replaced with padding
- Added display: grid and a gap between text and logos

**Comment by MaikenGunnerod** [comment]
Added rel="noreferrer" to all a elements:
- Good practice for security reasons
- Avoids information being leaked to third party sites when links are clicked

**Comment by MaikenGunnerod** [comment]
Changed capitalization on extra content buttons:
- Changed "tiktok" to "TikTok"

**Comment by MaikenGunnerod** [comment]
Updated extra content text:
- Changed "still extra content" text to "Check out OMO on these platforms"

**Comment by MaikenGunnerod** [comment]
Made border between sections shorter:
- Added "width: fit-content" on extra content section to fit border-top to video embed length

**Comment by MaikenGunnerod** [comment]
Removed border around extra content buttons:
- Removed transparent border
- Added extra padding on all sides (5px/0.5rem)
- Added "width: 25rem" to decrease the shifting of elements below when a button is in focus

**Review by Louis-Matsika — APPROVED** [review]

**Pull request merged**
